name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
  
      - name: Build for x86_64-unknown-linux-musl
        run: cargo build --release --target x86_64-unknown-linux-musl

      - run: mv target/x86_64-unknown-linux-musl/release/jyt jyt_${{ github.ref_name }}_x86_64-unknown-linux-musl

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: jyt_${{ github.ref_name }}_x86_64-unknown-linux-musl
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
