name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  build-wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: wasm32-wasi
    - name: Build
      run: cargo build --verbose --target wasm32-wasi

  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: cat ./examples/example.toml | cargo run ty

  run-wasm:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: wasm32-wasi
    - name: Build
      run: cargo build --verbose --target wasm32-wasi
    - run: brew install wasmer
    - run: cat ./examples/example.toml | wasmer run target/wasm32-wasi/debug/jyt.wasm ty

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features -- -D clippy::all -D warnings

  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
